[rocks]
busted = "2.2.0"
luacheck = "1.2.0"
nlua = "0.3.2"

[plugins]
"fidget.nvim" = "1.6.0"
"flutter-tools.nvim" = "1.14.0"
"lazydev.nvim" = "1.9.0"
#"mini.pairs" = "0.16.0"
"neorg" = "9.3.0"
"nvim-lspconfig" = "2.5.0"
"oil.nvim" = "2.15.0"
"rocks-config.nvim" = "3.1.2"
"rocks-dev.nvim" = "1.8.1"
"rocks-git.nvim" = "2.5.6"
"rocks-lazy.nvim" = "scm"
"rocks-treesitter.nvim" = "1.3.1"
"rocks.nvim" = "2.46.1"
"storm-mode.nvim" = { dir = "~/projects/personal/storm-mode.nvim" }
"telescope-undo.nvim" = "scm"
"telescope.nvim" = "scm"
# Treesitter Parsers
tree-sitter-asm = "0.0.31"
tree-sitter-awk = "0.0.32"
tree-sitter-bash = "0.0.44"
tree-sitter-cmake = "0.0.38"
tree-sitter-commonlisp = "scm"
tree-sitter-cpp = "0.0.46"
tree-sitter-css = "0.0.38"
tree-sitter-csv = "0.0.29"
tree-sitter-dart = "0.0.35"
tree-sitter-desktop = "0.0.21"
tree-sitter-diff = "0.0.32"
tree-sitter-dockerfile = "0.0.30"
tree-sitter-gdscript = "0.0.41"
tree-sitter-git_config = "0.0.31"
tree-sitter-git_rebase = "scm"
tree-sitter-gitcommit = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-go = "0.0.40"
tree-sitter-godot_resource = "0.0.35"
tree-sitter-gomod = "0.0.34"
tree-sitter-gosum = "scm"
tree-sitter-haskell = "0.0.33"
tree-sitter-html = "0.0.37"
tree-sitter-ini = "0.0.32"
tree-sitter-java = "0.0.43"
tree-sitter-javascript = "0.0.39"
tree-sitter-json = "0.0.37"
tree-sitter-json5 = "0.0.30"
tree-sitter-latex = "0.0.38"
tree-sitter-make = "scm"
tree-sitter-nginx = "0.0.30"
tree-sitter-nix = "0.0.64"
tree-sitter-ocaml = "scm"
tree-sitter-passwd = "0.0.29"
tree-sitter-perl = "0.0.46"
tree-sitter-python = "0.0.46"
tree-sitter-readline = "0.0.30"
tree-sitter-rst = "0.0.33"
tree-sitter-rust = "scm"
tree-sitter-sql = "0.0.41"
tree-sitter-ssh_config = "0.0.33"
tree-sitter-toml = "scm"
tree-sitter-xml = "0.0.40"
tree-sitter-yaml = "scm"
tree-sitter-jsonc = "0.0.29"
tree-sitter-typescript = "0.0.37"

[plugins."luvit-meta"]
git = "Bilal2453/luvit-meta"
rev = "1df30b60b1b4aecfebc785aa98943db6c6989716"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.10.0"

[config]
plugins_dir = "plugins"

[rocks_lazy]
import = "lazyplugins"

[treesitter]
auto_highlight = "all"
auto_install = "prompt"

[bundles]
lsp = { items = [ "nvim-lspconfig" ] }
telescope = { items = [ "telescope-undo.nvim", "telescope.nvim" ] }
